# Generated by Django 3.0.5 on 2020-05-05 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('school_address', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('school_code', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, upload_to='sample_image')),
                ('image2', models.ImageField(blank=True, upload_to='sample_image')),
                ('image3', models.ImageField(blank=True, upload_to='sample_image')),
                ('image4', models.ImageField(blank=True, upload_to='sample_image')),
                ('image5', models.ImageField(blank=True, upload_to='sample_image')),
                ('image6', models.ImageField(blank=True, upload_to='sample_image')),
                ('image7', models.ImageField(blank=True, upload_to='sample_image')),
                ('image8', models.ImageField(blank=True, upload_to='sample_image')),
                ('image9', models.ImageField(blank=True, upload_to='sample_image')),
                ('image10', models.ImageField(blank=True, upload_to='sample_image')),
                ('image11', models.ImageField(blank=True, upload_to='sample_image')),
                ('image12', models.ImageField(blank=True, upload_to='sample_image')),
                ('link_url1', models.URLField(blank=True, null=True)),
                ('link_url2', models.URLField(blank=True, null=True)),
                ('link_url3', models.URLField(blank=True, null=True)),
                ('link_url4', models.URLField(blank=True, null=True)),
                ('link_url5', models.URLField(blank=True, null=True)),
                ('link_url6', models.URLField(blank=True, null=True)),
                ('link_url7', models.URLField(blank=True, null=True)),
                ('link_url8', models.URLField(blank=True, null=True)),
                ('link_url9', models.URLField(blank=True, null=True)),
                ('link_url10', models.URLField(blank=True, null=True)),
                ('link_url11', models.URLField(blank=True, null=True)),
                ('link_url12', models.URLField(blank=True, null=True)),
                ('originalprice', models.FloatField()),
                ('discountedprice', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(max_length=250)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary')], max_length=1)),
                ('exam', models.CharField(choices=[('PR', 'Pri'), ('SR', 'Sec')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='default.JPG', upload_to='prof_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.BillingAddress')),
                ('items', models.ManyToManyField(to='pages.OrderItem')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
