# Generated by Django 3.0.5 on 2020-05-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200505_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='country',
        ),
        migrations.AddField(
            model_name='payment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
