# Generated by Django 3.0.5 on 2020-05-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
