# Generated by Django 3.0.5 on 2020-05-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200520_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='exam',
            field=models.CharField(choices=[('PR', 'Pri'), ('SR', 'Sec'), ('BO', 'Book')], max_length=2),
        ),
    ]
